apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: appone-service
  labels:
    app: appone
spec:
  ports:
  - port: 8083
    targetPort: 5000
  selector:
    app: appone
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: appone
  labels:
    app: appone
spec:
  containers:
  - name: appone-container
    image: fsadykov/docker-testing
    args: ["--name", "appone"]
