apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: apptwo-service
  labels:
    app: apptwo
spec:
  ports:
  - port: 8084
    targetPort: 5000
  selector:
    app: apptwo
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: apptwo
  labels:
    app: apptwo
spec:
  containers:
  - name: apptwo-container
    image: fsadykov/docker-testing
    args: ["--name", "apptwo"]
