apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: test
  name: fuchicorp-example
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"

spec:
  rules:

  - host: appone.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: appone-service
          servicePort: 8083

  - host: apptwo.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: apptwo-service
          servicePort: 8084
