apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fuchicorp-example
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:

  - host: appone.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: appone-service
          servicePort: 8081

  - host: apptwo.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: apptwo-service
          servicePort: 8082

  - host: appthree.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: appthree-service
          servicePort: 8083
