apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: appone-service
  labels:
    app: appone
spec:
  ports:
  - port: 8083
    targetPort: 5000
  selector:
    app: appone
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: appone
  labels:
    app: appone
spec:
  containers:
  - name: appone-container
    image: fsadykov/docker-testing
    args: ["--name", "appone"]
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: test
  name: fuchicorp-example
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: "24.12.115.204/32"
    # nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"

spec:
  rules:

  - host: appone.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: appone-service
          servicePort: 8083
